### ISSUE TITLE
Наименование переменной отличается от соглашения о кодировании

### ISSUE THREAD

**Issue by algolGuru** [maria-usynina/practice_TravelLine#1]
https://github.com/maria-usynina/practice_TravelLine/blob/501583fcf49399f08794b2ac2a8da6e8c645c85e/UniversityModelLib/UniversityModelLib/Faculty.cs#L11

**Comment by maria-usynina** [comment]
![image](https://user-images.githubusercontent.com/79213041/114009101-85e17500-986b-11eb-926a-bcc411f9c711.png)
