### ISSUE TITLE
Проблема с конструкторами

### ISSUE THREAD

**Issue by algolGuru** [maria-usynina/practice_TravelLine#10]
https://github.com/maria-usynina/practice_TravelLine/blob/48184001b42ec37350afb8d05c1395f1d7e1dd9c/UniversityModelLib/UniversityModelLib/Faculty.cs#L60

У вас есть лишний, пустой конструктор, и есть один хороший, который принимает имя учителя, почему бы просто не передать это имя в конструктор?

**Comment by maria-usynina** [comment]
![image](https://user-images.githubusercontent.com/79213041/114155690-6e1cf600-992a-11eb-9893-ed6b8b51bf90.png)
Ну, да, логично, исправила
