### ISSUE TITLE
Название переменной v не информативно

### ISSUE THREAD

**Issue by algolGuru** [maria-usynina/practice_TravelLine#2]
https://github.com/maria-usynina/practice_TravelLine/blob/501583fcf49399f08794b2ac2a8da6e8c645c85e/UniversityModelLib/UniversityModelLib/Faculty.cs#L17

**Comment by maria-usynina** [comment]
![image](https://user-images.githubusercontent.com/79213041/114009363-c04b1200-986b-11eb-8f46-17dc30d8de63.png)
