### ISSUE TITLE
Надо уточнить для чего используется данный конструктор

### ISSUE THREAD

**Issue by algolGuru** [maria-usynina/practice_TravelLine#3]
https://github.com/maria-usynina/practice_TravelLine/blob/501583fcf49399f08794b2ac2a8da6e8c645c85e/UniversityModelLib/UniversityModelLib/Faculty.cs#L13

Смущает, что конструктор пустой. Напишите, для чего он был создан.

**Comment by maria-usynina** [comment]
В файле University.cs не указала переменную facultyName в Faculty faculty = new(facultyName). Студия подсказала добавить пустой конструктор. Забыла исправить этот недочет.
