### ISSUE TITLE
Название переменной

### ISSUE THREAD

**Issue by algolGuru** [maria-usynina/practice_TravelLine#4]
https://github.com/maria-usynina/practice_TravelLine/blob/501583fcf49399f08794b2ac2a8da6e8c645c85e/UniversityModelLib/UniversityModelLib/Faculty.cs#L48

**Comment by maria-usynina** [comment]
![image](https://user-images.githubusercontent.com/79213041/114010353-b1189400-986c-11eb-8fe9-b4066884e46d.png)
Заменила на переменную teacherName
