### ISSUE TITLE
Попробуйте использовать конструкцию foreach

### ISSUE THREAD

**Issue by algolGuru** [maria-usynina/practice_TravelLine#5]
https://github.com/maria-usynina/practice_TravelLine/blob/501583fcf49399f08794b2ac2a8da6e8c645c85e/UniversityModelLib/UniversityModelLib/Faculty.cs#L50

Конструкция for читается тяжелее. Для перебора всех элементов коллекции можно воспользоваться конструкцией foreach.

**Comment by maria-usynina** [comment]
![image](https://user-images.githubusercontent.com/79213041/114010546-df966f00-986c-11eb-9eff-f5cd8f060e82.png)
