### ISSUE TITLE
Наименование переменной

### ISSUE THREAD

**Issue by algolGuru** [maria-usynina/practice_TravelLine#6]
https://github.com/maria-usynina/practice_TravelLine/blob/501583fcf49399f08794b2ac2a8da6e8c645c85e/UniversityModelLib/UniversityModelLib/IUniversity.cs#L11

**Comment by maria-usynina** [comment]
![image](https://user-images.githubusercontent.com/79213041/114010630-fe950100-986c-11eb-844b-26bfa087ddc7.png)
Заменила на переменную facultyName
