### ISSUE TITLE
Метод нигде не используется

### ISSUE THREAD

**Issue by algolGuru** [maria-usynina/practice_TravelLine#7]
https://github.com/maria-usynina/practice_TravelLine/blob/501583fcf49399f08794b2ac2a8da6e8c645c85e/UniversityModelLib/UniversityModelLib/IUniversity.cs#L13

**Comment by maria-usynina** [comment]
![image](https://user-images.githubusercontent.com/79213041/114010810-33a15380-986d-11eb-9727-f67bbbfe82a9.png)
Используется
