### ISSUE TITLE
Слишком сложный метод

### ISSUE THREAD

**Issue by algolGuru** [maria-usynina/practice_TravelLine#8]
https://github.com/maria-usynina/practice_TravelLine/blob/501583fcf49399f08794b2ac2a8da6e8c645c85e/UniversityModelLib/UniversityModelLib/University.cs#L32

1) Метод слишком большой
2) Высокий уровень вложенности

**Comment by maria-usynina** [comment]
Разбила данный метод, пришлось добавить новый интерфейс IPerson и класс Person
