### ISSUE TITLE
Постарайтесь упростить метод Main

### ISSUE THREAD

**Issue by algolGuru** [maria-usynina/practice_TravelLine#9]
https://github.com/maria-usynina/practice_TravelLine/blob/501583fcf49399f08794b2ac2a8da6e8c645c85e/UniversityModelLib/UniversityModel/Program.cs#L9

Надо стараться делать функцию Main меньше. 
Разделите код на функции.

**Comment by maria-usynina** [comment]
Постаралась уменьшить функцию
